# Generated by Django 4.2.8 on 2023-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='f')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
