# Generated by Django 4.2.8 on 2024-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
