# Generated by Django 4.2.8 on 2024-02-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_uploadedcsv_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='is_deleted',
        ),
    ]
